#default values. Can be overridden with the -D in the jvm-arguments

config.path: "/Users/simon/Desktop/Projects/Mailprocessor/Configuration/configuration.yml"
semantic.url: "http://localhost:8081/api/rest/1.0/classifyText"


logging.level:
  root: WARN
  com.cuupa.mailprocessor: DEBUG


camunda:
  bpm.job-execution.enabled: true
  bpm:
    filter:
      create: All tasks
    admin-user:
      id: demo
      password: demo
      first-name: demo
      last-name: demo
    database:
      type: postgres

spring:
  application:
    name: mailprocessor

  datasource:
    url: jdbc:postgresql://10.80.22.5:5433/mailprocessor
    username: mailprocessor-postgresql
    password: Q!ZGRfn8
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
