#default values. Can be overridden with the -D in the jvm-arguments

config.path: "docker/configuration.yml"
semantic.url: "http://localhost:8081/api/rest/1.0/classifyText"


logging.level:
  root: WARN
  com.cuupa.mailprocessor: DEBUG


camunda:
  bpm.job-execution.enabled: true
  bpm:
    filter:
      create: All tasks
    admin-user:
      id: demo
      password: demo
      first-name: demo
      last-name: demo

spring:
  application:
    name: mailprocessor

  datasource:
    url: jdbc:h2:file:./camunda-h2-database
