#default values. Can be overridden with the -D in the jvm-arguments
server.port: 8080

logging.level:
  root: ERROR
  com.cuupa.mailprocessor: WARN

mailprocessor:
  config: /opt/mailprocessor/config.json

camunda:
  bpm.job-execution.enabled: true